### ISSUE TITLE
fold, call, raiseのいずれかを押したらランダムでカードが表示されるようにする

### ISSUE THREAD

**Issue by osatoh** [osatoh/starting_hands_ui#2]
## 背景
配列から消したりはしなくていいので、とにかくボタンを押したらランダムに表示されるようにする
その際、先にstartのボタンは押す必要がありそう
じゃないとstateが保持できない

## TODO
- [ ] カード2枚分の箱の実装(中身は表示できてなくていい)
- [ ] start, fold, call, raiseのボタンを用意する
- [ ] startを押したらカードが表示される(stateかな？ランダムで表示)
- [ ] fold, call, raiseのいずれかを押したらランダムでカードが表示される

_Originally posted by @osatoh in https://github.com/osatoh/starting_hands_ui/issues/1#issuecomment-955768864_

**Comment by osatoh** [comment]
[Grid Lists \- Official Tailwind CSS UI Components](https://tailwindui.com/components/application-ui/lists/grid-lists#component-5d72b187beb968e12db89fe49f272b18)
![image](https://user-images.githubusercontent.com/67081565/139597160-7c207eff-bdc4-49cd-8d3f-c7c5e07e88b5.png)


```js
/* This example requires Tailwind CSS v2.0+ */
import { MailIcon, PhoneIcon } from '@heroicons/react/solid'

const people = [
  {
    name: 'Jane Cooper',
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    telephone: '+1-202-555-0170',
    imageUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60',
  },
  // More people...
]

export default function Example() {
  return (
    <ul role="list" className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
      {people.map((person) => (
        <li
          key={person.email}
          className="col-span-1 flex flex-col text-center bg-white rounded-lg shadow divide-y divide-gray-200"
        >
          <div className="flex-1 flex flex-col p-8">
            <img className="w-32 h-32 flex-shrink-0 mx-auto rounded-full" src={person.imageUrl} alt="" />
            <h3 className="mt-6 text-gray-900 text-sm font-medium">{person.name}</h3>
            <dl className="mt-1 flex-grow flex flex-col justify-between">
              <dt className="sr-only">Title</dt>
              <dd className="text-gray-500 text-sm">{person.title}</dd>
              <dt className="sr-only">Role</dt>
              <dd className="mt-3">
                <span className="px-2 py-1 text-green-800 text-xs font-medium bg-green-100 rounded-full">
                  {person.role}
                </span>
              </dd>
            </dl>
          </div>
          <div>
            <div className="-mt-px flex divide-x divide-gray-200">
              <div className="w-0 flex-1 flex">
                <a
                  href={`mailto:${person.email}`}
                  className="relative -mr-px w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-bl-lg hover:text-gray-500"
                >
                  <MailIcon className="w-5 h-5 text-gray-400" aria-hidden="true" />
                  <span className="ml-3">Email</span>
                </a>
              </div>
              <div className="-ml-px w-0 flex-1 flex">
                <a
                  href={`tel:${person.telephone}`}
                  className="relative w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-br-lg hover:text-gray-500"
                >
                  <PhoneIcon className="w-5 h-5 text-gray-400" aria-hidden="true" />
                  <span className="ml-3">Call</span>
                </a>
              </div>
            </div>
          </div>
        </li>
      ))}
    </ul>
  )
}
```
一旦カードっぽいtailwindを使ってみる

**Comment by osatoh** [comment]
[\[CSS/HTML\]上下左右中央揃えまとめ。 \- Qiita](https://qiita.com/super-mana-chan/items/0d35a0b9ac1bf97593c8#%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E3%82%BB%E3%83%AB%E8%A6%81%E7%B4%A0%E3%81%AE%E5%A0%B4%E5%90%88)

中央よせ

![image](https://user-images.githubusercontent.com/67081565/139598111-dd029317-57af-4f08-b41d-4a0631014fb9.png)

次はアクションのボタンを用意する

**Comment by osatoh** [comment]
![image](https://user-images.githubusercontent.com/67081565/139627039-5197c723-97a7-4912-8593-d3ab25399618.png)

現状こんな感じ
カードとボタンの間にスペース開けたいのと、ショートカット作りたい

**Comment by osatoh** [comment]
まず、ボタンを押したらランダムでカードを表示するようにする
1. foldをclickする
2. set = cardsから選んだ配列
3. setから必要な要素を表示
4. foldを押したらfalses配列に追加
5. 1に戻る

ってイメージで実装してみる

**Comment by osatoh** [comment]
[![Image from Gyazo](https://i.gyazo.com/f04abf41453bc043aeb10de480a7071f.gif)](https://gyazo.com/f04abf41453bc043aeb10de480a7071f)

fold押して、カードがランダムに表示できるようになった
次は削除の関数だな
正解の配列用意して
openの場合
handをfoldした時
- handが正解の配列に含まれていなければ
  - 該当ハンドを元の配列から削除
handをraiseした時
- handが正解の配列に含まれていれば
  - 該当ハンドを元の配列から削除

vs tight or looseの場合
handをfoldした場合
handをfoldした時
- handがrailse_handsまたはcall_handsに含まれていなければ
  - 該当ハンドを元の配列から削除
handをcallした時
- handがcall_handsに含まれていれば
  - 該当ハンドを元の配列から削除
handをraiseした時
- handがrailse_handsに含まれていれば
  - 該当ハンドを元の配列から削除
